import { Activity, Database, DatabaseZap, Download, LayoutGrid, LineChart, Settings, Users } from "lucide-react";

export const consoleDirectory = [
  { path: "/console", label: "Dashboard", group: "Overview", icon: LayoutGrid, purpose: "Start with workspace readiness, priorities, and the next useful action.", next: "/operations", entries: [{ label: "Workspace overview", href: "/console", purpose: "Connections, warehouse readiness, performance, and current work." }] },
  { path: "/operations", label: "Operations", group: "Overview", icon: Activity, purpose: "Understand which stage of your data workflow needs attention.", next: "/sources", entries: [{ label: "Health & next actions", href: "/operations", purpose: "Authorization, freshness, ingestion, report readiness, and delivery evidence." }] },
  { path: "/sources", label: "Sources", group: "Pipelines", icon: DatabaseZap, purpose: "Connect providers, manage account access, and fix source problems.", next: "/explorer", entries: [{ label: "Your sources", href: "/sources?tab=connected", purpose: "Review connected sources and resolve connection issues." }, { label: "Client accounts", href: "/sources?tab=accounts", purpose: "Discover accounts and review client assignments." }, { label: "Integration library", href: "/sources?tab=available", purpose: "Browse supported providers and start source setup." }, { label: "Needs attention", href: "/sources?tab=attention", purpose: "Connections with access, freshness, or partial-data issues." }] },
  { path: "/reports", label: "Reports", group: "Pipelines", icon: LineChart, purpose: "Review client performance and the evidence behind reporting.", next: "/exports", entries: [{ label: "Performance", href: "/reports?view=performance", purpose: "Performance totals by currency, campaign comparisons, and downloads." }, { label: "Report readiness", href: "/reports?view=readiness", purpose: "Check account coverage for a client window, inspect gaps, and verify a scoped recovery." }, { label: "Sync activity", href: "/reports?view=sync", purpose: "Import history, errors, and diagnostic receipts." }] },
  { path: "/explorer", label: "Data explorer", group: "Data", icon: Database, purpose: "Inspect and filter imported warehouse rows before relying on a report.", next: "/reports", entries: [{ label: "Warehouse & metrics", href: "/explorer", purpose: "Account/date/platform filters, columns, rows, CSV/Excel, and import controls." }] },
  { path: "/exports", label: "Exports & API", group: "Data", icon: Download, purpose: "Use the warehouse in Google Sheets, Looker Studio, or your API workflow.", next: "/settings?tab=api", entries: [{ label: "Destination directory", href: "/exports", purpose: "Connector availability, plan requirements, and setup guidance." }, { label: "Workspace API keys", href: "/settings?tab=api", purpose: "Manage destination credentials in the existing settings screen." }] },
  { path: "/clients", label: "Clients", group: "Management", icon: Users, purpose: "Organize client accounts, portfolio health, and reporting scope.", next: "/sources?tab=accounts", entries: [{ label: "Client & workspace portfolio", href: "/clients", purpose: "Client directory, readiness, assignments, and portfolio controls." }] },
  { path: "/settings", label: "Settings", group: "Management", icon: Settings, purpose: "Manage workspace identity, people, billing, security, and data rules.", next: "/console", entries: [{ label: "Workspace", href: "/settings?tab=workspace", purpose: "Workspace identity and setup." }, { label: "Clients", href: "/settings?tab=clients", purpose: "Existing client management controls." }, { label: "Team", href: "/settings?tab=team", purpose: "Membership and invitations." }, { label: "Data quality", href: "/settings?tab=alerts", purpose: "Quality rules and alert configuration." }, { label: "Billing", href: "/settings?tab=billing", purpose: "Plan, usage, payment history, and plan management." }, { label: "API keys", href: "/settings?tab=api", purpose: "Destination credentials and key controls." }, { label: "Sessions", href: "/settings?tab=sessions", purpose: "Session security and login history." }] },
] as const;

export function directoryFor(path: string) {
  return consoleDirectory.find(section => path === section.path || path.startsWith(`${section.path}/`));
}
