import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Plug, RefreshCw, BarChart3, Key, Clock, ShieldCheck } from "lucide-react";
import { PRODUCT_SITE_URL } from "@/lib/site-url";

export const metadata: Metadata = {
    title: "How Monstera works",
    description: "Connect certified advertising and marketplace sources, verify warehouse imports, and report through Google Sheets or Looker Studio.",
    alternates: { canonical: `${PRODUCT_SITE_URL}/platform` },
};

const steps = [
    {
        icon: Plug,
        title: "1. Connect your ad platforms",
        body: "Choose a certified Meta Ads, Google Ads, TikTok Ads, or Shopee workflow. Complete the provider authorization and confirm the connection appears in the intended workspace.",
    },
    {
        icon: RefreshCw,
        title: "2. Sync your data",
        body: "Choose a bounded date window and run a warehouse import. Data coverage varies by provider; each run records its final outcome so you can verify it before reporting.",
    },
    {
        icon: Key,
        title: "3. Choose destination authentication",
        body: "Looker Studio uses a revocable workspace API key. The Google Sheets add-on uses a Google identity token generated by Apps Script; you do not paste that token into the sidebar.",
    },
    {
        icon: BarChart3,
        title: "4. Build reports",
        body: "Query the verified warehouse rows through the chosen destination, then reconcile the first report against Data Explorer before sharing it.",
    },
];

const capabilities = [
    {
        icon: Clock,
        title: "Scheduled syncs",
        body: "Refresh behavior and configured limits vary by plan. Review the plan table and the current product state before relying on a cadence.",
    },
    {
        icon: ShieldCheck,
        title: "Credential security",
        body: "OAuth tokens and API keys are encrypted at rest and scoped per workspace. Revoke any key from Settings at any time.",
    },
    {
        icon: BarChart3,
        title: "Multi-platform in one report",
        body: "Meta Ads, Google Ads, and TikTok data share a consistent schema — dimensions like date, platform, campaign, and ad set work the same way across all sources.",
    },
    {
        icon: RefreshCw,
        title: "Sync logs",
        body: "Every pipeline run records the number of rows synced, errors, and timestamps. Re-trigger any failed run directly from the console.",
    },
];

export default function PlatformPage() {
    return (
        <div className="mx-auto max-w-4xl px-6 pt-28 pb-24 font-sans text-ink">
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full border border-line bg-panel text-ink-mute text-xs font-semibold uppercase tracking-wider mb-3">
                <span className="w-1.5 h-1.5 rounded-full bg-accent"></span>
                <span>How it works</span>
            </div>
            <h1 className="mt-2 text-3xl font-bold tracking-tight text-ink sm:text-4xl">
                Ad data, where you already work
            </h1>
            <p className="mt-4 text-sm sm:text-base text-ink-mute leading-relaxed max-w-2xl font-normal">
                Monstera connects your ad platforms to the reporting tools your team already uses —
                Looker Studio and Google Sheets — with a managed, workspace-scoped warehouse instead of custom ETL code.
            </p>

            {/* Steps */}
            <div className="mt-12 space-y-4">
                {steps.map((step) => {
                    const Icon = step.icon;
                    return (
                        <div
                            key={step.title}
                            className="flex gap-4 rounded-lg border border-line bg-panel p-6"
                        >
                            <div className="w-10 h-10 rounded-md bg-canvas border border-line flex items-center justify-center shrink-0 text-accent">
                                <Icon className="h-5 w-5" aria-hidden />
                            </div>
                            <div>
                                <h2 className="text-sm font-bold text-ink">{step.title}</h2>
                                <p className="mt-1 text-xs text-ink-mute leading-relaxed">{step.body}</p>
                            </div>
                        </div>
                    );
                })}
            </div>

            {/* Capabilities */}
            <h2 className="mt-16 text-xl font-bold text-ink">What's included</h2>
            <div className="mt-6 grid gap-4 sm:grid-cols-2">
                {capabilities.map((cap) => {
                    const Icon = cap.icon;
                    return (
                        <div
                            key={cap.title}
                            className="rounded-lg border border-line bg-panel p-5"
                        >
                            <Icon className="h-4 w-4 text-accent mb-3" aria-hidden />
                            <h3 className="text-sm font-semibold text-ink">{cap.title}</h3>
                            <p className="mt-1 text-xs text-ink-mute leading-relaxed">{cap.body}</p>
                        </div>
                    );
                })}
            </div>

            {/* CTA */}
            <div className="mt-14 flex flex-col sm:flex-row gap-3">
                <Link
                    href="/register"
                    className="inline-flex items-center justify-center gap-2 rounded-md bg-white hover:bg-neutral-200 px-6 py-2.5 text-xs font-semibold text-black transition-colors shadow-xs"
                >
                    Start free pilot
                    <ArrowRight className="h-3.5 w-3.5" aria-hidden />
                </Link>
                <Link
                    href="/looker-studio"
                    className="inline-flex items-center justify-center gap-2 rounded-md border border-line bg-panel hover:bg-[#16181c] px-6 py-2.5 text-xs font-semibold text-ink transition-colors"
                >
                    Looker Studio guide
                </Link>
            </div>
        </div>
    );
}
