import type { CapabilityReasonCode } from "./types";

export const CAPABILITY_REASON_CODES = {
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
  UNKNOWN_PROVIDER: "UNKNOWN_PROVIDER",
  UNKNOWN_REPORT_SURFACE: "UNKNOWN_REPORT_SURFACE",
  UNKNOWN_CAPABILITY: "UNKNOWN_CAPABILITY",
  CAPABILITY_RETIRED: "CAPABILITY_RETIRED",
  ATTRIBUTION_WINDOW_RETIRED: "ATTRIBUTION_WINDOW_RETIRED",
  UNKNOWN_ATTRIBUTION_WINDOW: "UNKNOWN_ATTRIBUTION_WINDOW",
  ATTRIBUTION_WINDOW_NOT_ALLOWED: "ATTRIBUTION_WINDOW_NOT_ALLOWED",
  ATTRIBUTION_WINDOW_FORBIDDEN_COMBINATION:
    "ATTRIBUTION_WINDOW_FORBIDDEN_COMBINATION",
  GRANULARITY_NOT_SUPPORTED: "GRANULARITY_NOT_SUPPORTED",
  LOOKBACK_LIMIT_EXCEEDED: "LOOKBACK_LIMIT_EXCEEDED",
} as const satisfies Record<string, CapabilityReasonCode>;

/**
 * Machine-readable tokens embedded in construction-time TypeError messages.
 * These are registry-authoring failures, not evaluation findings, so they are
 * kept separate from CAPABILITY_REASON_CODES.
 */
export const CAPABILITY_REGISTRY_ERROR_CODES = {
  DUPLICATE_CAPABILITY_RECORD_ID: "DUPLICATE_CAPABILITY_RECORD_ID",
  AMBIGUOUS_CAPABILITY_SELECTOR: "AMBIGUOUS_CAPABILITY_SELECTOR",
} as const;
