import type { CapabilityReasonCode } from "./types";

export const CAPABILITY_REASON_CODES = {
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
  UNKNOWN_PROVIDER: "UNKNOWN_PROVIDER",
  UNKNOWN_REPORT_SURFACE: "UNKNOWN_REPORT_SURFACE",
  UNKNOWN_CAPABILITY: "UNKNOWN_CAPABILITY",
  CAPABILITY_RETIRED: "CAPABILITY_RETIRED",
  ATTRIBUTION_WINDOW_RETIRED: "ATTRIBUTION_WINDOW_RETIRED",
  GRANULARITY_NOT_SUPPORTED: "GRANULARITY_NOT_SUPPORTED",
  LOOKBACK_LIMIT_EXCEEDED: "LOOKBACK_LIMIT_EXCEEDED",
} as const satisfies Record<string, CapabilityReasonCode>;
